# Generated by Django 5.0.4 on 2024-04-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='payment_url',
            field=models.TextField(blank=True, null=True, verbose_name='ссылка для оплаты'),
        ),
    ]
