# Generated by Django 5.0.4 on 2024-04-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing_info',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ответ для теста'),
        ),
    ]
