# Generated by Django 5.0.4 on 2024-04-23 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_info', '0002_testing_info_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=100, null=True, verbose_name='ответ пользователя')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_info.testing_info', verbose_name='ответ пользователя')),
            ],
        ),
    ]
